server:
  forward-headers-strategy: framework

spring:
  datasource:
    url: ${MYSQL_PROD_URL}  # MySQL 데이터베이스 URL
  data:
    redis:
      host: hyetaekon-redis
      password: ${REDIS_PASSWORD}


jwt:
  access-expired: 1800 # 30분
  refresh-expired: 86400  # 1일

app:
  cookie:
    secure: true
    same-site: None